services:
  - type: web
    name: traffic-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
    plan: free
    rootDir: backend
  - type: web
    name: traffic-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    envVars:
      - key: PORT
        value: 3000
    plan: free
    rootDir: frontend